source 'https://rubygems.org'

gem 'rails'
gem 'pg'
gem 'sass-rails'
gem 'bootstrap-sass'
gem 'sprockets'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem 'pry'
gem 'smarter_csv'
gem 'devise'
gem 'therubyracer'
gem 'omniauth'
gem 'omniauth-github'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'quiet_assets'
end

group :test, :development do
  gem 'rspec-rails'
  gem 'dotenv-rails'
end

group :test do
  gem 'shoulda-matchers'
end
